package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"bidding-service/graph/model"
	"context"
	"fmt"
	"time"
)

// Bids is the resolver for the bids field.
func (r *auctionResolver) Bids(ctx context.Context, obj *model.Auction) ([]*model.Bid, error) {
	// Initialize as an empty slice to ensure you get [] and not null in the response
	bids := []*model.Bid{}

	// Querying PostgreSQL using the ID passed from the parent Auction
	query := `SELECT id, amount, bidder_id, created_at FROM bids WHERE auction_id = $1`
	rows, err := r.DB.QueryContext(ctx, query, obj.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var b model.Bid
		var createdAt time.Time
		if err := rows.Scan(&b.ID, &b.Amount, &b.BidderID, &createdAt); err != nil {
			return nil, err
		}
		b.Timestamp = createdAt.Format(time.RFC3339)
		bids = append(bids, &b)
	}

	return bids, nil
}

// PlaceBid is the resolver for the placeBid field.
func (r *mutationResolver) PlaceBid(ctx context.Context, auctionID string, amount float64) (*model.Bid, error) {
	query := `INSERT INTO bids (auction_id, amount, bidder_id, created_at) 
              VALUES ($1, $2, $3, $4) RETURNING id`
	var id string
	err := r.DB.QueryRowContext(ctx, query, auctionID, amount, "user-123", time.Now()).Scan(&id)
	if err != nil {
		return nil, fmt.Errorf("database error: %w", err)
	}

	return &model.Bid{
		ID:        id,
		Amount:    amount,
		BidderID:  "user-123",
		Timestamp: time.Now().Format(time.RFC3339),
	}, nil
}

// ActiveAuctions is the resolver for the activeAuctions field.
func (r *queryResolver) ActiveAuctions(ctx context.Context) ([]*model.Auction, error) {
	// This is primarily handled by the Inventory service, returning empty slice
	return []*model.Auction{}, nil
}

// Auction is the resolver for the auction field.
func (r *queryResolver) Auction(ctx context.Context, id string) (*model.Auction, error) {
	// We only return the ID.
	// The AuctionResolver.Bids function we just wrote will fetch the actual bids.
	return &model.Auction{ID: id}, nil
}

// Auction returns AuctionResolver implementation.
func (r *Resolver) Auction() AuctionResolver { return &auctionResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type auctionResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
