package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"bidding-service/graph/model"
	"context"
	"fmt"
)

// FindAuctionByID is the resolver for the findAuctionByID field.
func (r *entityResolver) FindAuctionByID(ctx context.Context, id string) (*model.Auction, error) {
	panic(fmt.Errorf("not implemented: FindAuctionByID - findAuctionByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
