package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"bidding-service/graph/model"
	"context"
	"fmt"
	"time"
)

// Bids is the resolver for the bids field.
func (r *auctionResolver) Bids(ctx context.Context, obj *model.Auction) ([]*model.Bid, error) {
	// 1. Initialize empty slice (prevents null in JSON)
	bids := []*model.Bid{}

	// 2. Query PostgreSQL using the ID from the Auction object
	// The obj.ID here comes from what FindAuctionByID returned
	query := `SELECT id, amount, bidder_id, created_at FROM bids WHERE auction_id = $1`
	rows, err := r.DB.QueryContext(ctx, query, obj.ID)
	if err != nil {
		fmt.Println("❌ Database Error:", err)
		return nil, err
	}
	defer rows.Close()

	// 3. Scan rows into the model
	for rows.Next() {
		var b model.Bid
		var createdAt time.Time
		if err := rows.Scan(&b.ID, &b.Amount, &b.BidderID, &createdAt); err != nil {
			return nil, err
		}
		b.Timestamp = createdAt.Format(time.RFC3339)
		bids = append(bids, &b)
	}

	return bids, nil
}

// PlaceBid is the resolver for the placeBid field.
// PlaceBid is the resolver for the placeBid field.
func (r *mutationResolver) PlaceBid(ctx context.Context, auctionID string, amount float64) (*model.Bid, error) {
	// 1. Create a timestamp for the bid
	now := time.Now()

	// 2. Prepare the SQL query to insert into your 'bids' table
	// We assume 'user-123' for now; in a real app, you'd get this from the Auth context
	query := `INSERT INTO bids (auction_id, amount, bidder_id, created_at) 
              VALUES ($1, $2, $3, $4) 
              RETURNING id`

	var id string
	err := r.DB.QueryRowContext(ctx, query, auctionID, amount, "user-123", now).Scan(&id)

	if err != nil {
		fmt.Println("❌ Error inserting bid:", err)
		return nil, fmt.Errorf("failed to place bid: %w", err)
	}

	// 3. Return the newly created Bid object
	return &model.Bid{
		ID:        id,
		Amount:    amount,
		BidderID:  "user-123",
		Timestamp: now.Format(time.RFC3339),
	}, nil
}

// ServiceMetadata is the resolver for the _serviceMetadata field.
func (r *queryResolver) ServiceMetadata(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: ServiceMetadata - _serviceMetadata"))
}

// Auction returns AuctionResolver implementation.
func (r *Resolver) Auction() AuctionResolver { return &auctionResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type auctionResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
