// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auction struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	Description   *string `json:"description,omitempty"`
	StartingPrice float64 `json:"startingPrice"`
	EndTime       string  `json:"endTime"`
	Bids          []*Bid  `json:"bids,omitempty"`
}

func (Auction) IsEntity() {}

type Bid struct {
	ID        string  `json:"id"`
	Amount    float64 `json:"amount"`
	BidderID  string  `json:"bidderId"`
	Timestamp string  `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}
